Repository braydenidzenga/ZettaNote, pull requests merged in 2025-10, with the labels that each got.

#22 Enhance backend usability: Improved root route & added auth safety checks 🚀
  backend/app.js
  backend/routes/auth/auth.js
  backend/routes/auth/login.js
  backend/routes/auth/signup.js
Labels: hacktoberfest

#31 feat: enhance landing page with modern UI and animations
  frontend/src/pages/landingpage.jsx
Labels: hacktoberfest

#33 Fix:24-Optiomized-Signup
  backend/routes/auth/signup.js
Labels: hacktoberfest

#37 Added delete User Route
  backend/routes/auth/auth.js
  backend/routes/auth/deleteUser.js
Labels: hacktoberfest2025

#36 Feat:27-added-delete-page-btn
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ui/pageView.jsx
Labels: hacktoberfest2025

#51 feat: Enhanced UI/UX with modern design and toast notifications
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/ui/headerbar.jsx
  frontend/src/components/ui/newPagePopup.jsx
  frontend/src/components/ui/pageView.jsx
  frontend/src/components/ui/sharePageButton.jsx
  frontend/src/components/ui/sidebar.jsx
  frontend/src/pages/home.jsx
  frontend/src/utils/toast.js
Labels: hacktoberfest2025

#61 feat: conditional rendering for pages
  README.md
  backend/app.js
  backend/config.js
  backend/models/Page.js
  backend/models/User.js
  backend/routes/auth/auth.js
  backend/routes/auth/changePassword.js
  backend/routes/auth/deleteUser.js
  backend/routes/auth/getUser.js
  backend/routes/auth/login.js
  backend/routes/auth/signup.js
  backend/routes/pages/createPage.js
  backend/routes/pages/deletePage.js
  backend/routes/pages/getPages.js
  backend/routes/pages/pages.js
  backend/routes/pages/renamePage.js
  backend/routes/pages/savePage.js
  backend/routes/pages/sharePage.js
  backend/util/token.js
  backend/util/validatePass.js
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/App.js
  frontend/src/components/ProtectedRoute.jsx
  frontend/src/components/ui/Navbar.jsx
  frontend/src/components/ui/ThemeContext.jsx
  frontend/src/components/ui/headerbar.jsx
  frontend/src/components/ui/newPagePopup.jsx
  frontend/src/components/ui/pageView.jsx
  frontend/src/components/ui/provider.jsx
  frontend/src/components/ui/sharePageButton.jsx
  frontend/src/components/ui/sidebar.jsx
  frontend/src/config.js
  frontend/src/index.js
  frontend/src/pages/home.jsx
  frontend/src/pages/landingpage.jsx
  frontend/src/pages/login.jsx
  frontend/src/pages/signup.jsx
  frontend/src/utils/auth.js
  frontend/src/utils/toast.js
Labels: format

#107 Readme file enhanced ✨
  README.md
Labels: hacktoberfest-accepted
